# site properties and page defaults
title: Anna Prieto Colomina
subtitle: Biomedical Scientist | Neurodevelopment | Pediatric Brain Tumors
description: Hi! I’m a neuroscientist focused on pediatric brain tumors (ETMR), multi-omics, and translational models.  
- PhD candidate, Instituto de Neurociencias (CSIC-UMH)  
- Interests: LIN28/let-7 axis, Dicer, scRNA-seq, in vivo models 
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: anprieco@gmail.com
  orcid: 0000-0001-8713-9213
  google-scholar: https://scholar.google.com/citations?user=8HR8AqkAAAAJ&hl=es 
  github: https://github.com/anprieco
  twitter: https://x.com/annaprico
  bluesky: https://bsky.app/profile/annaprico.bsky.social

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
