# site properties and page defaults
title: "Anna Prieto Colomina"
subtitle: "Biomedical Scientist | Neurodevelopment | Pediatric Brain Tumors"
description: "Hi! I’m a neuroscientist focused on pediatric brain tumors (ETMR), multi-omics, and translational models. PhD candidate, Instituto de Neurociencias (CSIC-UMH). Interest in LIN28/let-7 axis, Dicer, scRNA-seq and in vivo models."
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: anprieco@gmail.com
  orcid: 0000-0001-8713-9213
  google-scholar: 8HR8AqkAAAAJ
  github: anprieco
  twitter: annaprico
  bluesky: annaprico.bsky.social

### jekyll settings
# front matter defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: "members"
    values:
      layout: member
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  members:
    output: true
  posts:
    output: true

plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

highlighter: rouge
theme: null

sass:
  sass_dir: _styles

include:
  - _styles
  - _scripts

exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
