- doi: 10.3389/fcell.2024.1464932
  image: /images/hugo.png
- doi: 10.1126/sciadv.adn9998
  image: /images/Lucia.png
- doi: 10.1126/sciadv.abj4010
  image: /images/Kaviya.png
- doi: 10.1002/bies.202100073
  image: /images/Prieto.jpg
- doi: 10.15252/embj.2020105479
  image: /images/virginia.png
